### ISSUE TITLE
환자정보에 보호자 연락처 추가

### ISSUE THREAD

**Issue by cloudwisx** [SNUH-SMILE/web-app#12]
### 환자정보에 보호자 연락처 추가
1. ER-Diagram 수정
2. 환자(PATIENT) 테이블에 보호자 연락처(GUARDIAN_CELL_PHONE) 추가
3. 회원가입, 회원정보 수정 API 수정 (화용, 우영)

- 회원가입, 회원정보 수정 API 분리여부 검토
1. 상대] 회원가입, 회원정보 수정 각 API에서 Request Parameter의 유효성 검사항목이 달라 분리하는게 맞는거 같음
2. 화용] 회원가입, 수정 API 분리
             동일 VO 사용 및 Valid Group 처리하여 유효성 검사 하는 방향으로 생각하고 있습니다.
3. 우영] 회원정보 수정할때 다른항목이 추가될수도있으니까 분리하는게 좋은거 같습니다.
4. 결론] API를 분리하기로 결정

**Comment by cloudwisx** [comment]
12/7(화), 이상대]
1. ER-Diagram 수정
2. 환자(PATIENT) 테이블에 보호자 연락처(GUARDIAN_CELL_PHONE) 추가

**Comment by cloudwisx** [comment]
12/9(목), 이상대]
1. 회원가입, 회원정보 수정 API 분리
2. 회원가입, 회원정보 수정 API에 보호자 연락처(gurdianCellPhone) Request Parameter 추가
3. [IITP 감염병_REST API 정의서_v0.3.xlsx](https://github.com/SNUH-SMILE/web-app/files/7681802/IITP._REST.API._v0.3.xlsx)

**Comment by developer-Fwa** [comment]
12/09(목), 심화용]
#2 1aec241 소스반영..
