### ISSUE TITLE
보안기능 개발

### ISSUE THREAD

**Issue by cloudwisx** [SNUH-SMILE/web-app#19]
- 로그인시 Token을 발행하여 Body에 담아 응답. Token의 만료시간은 24시간
- 로그인을 제외한 모든 요청시 Header에(Key: Authorization, Value: bearer Token) Token을 담아 요청
- Token의 유효성 검사
  1. web-app에서 발행하지 않았거나 유효하지 않은 Token인 경우: 해당 정보에 대한 결과코드/메시지를 Body에 담아 응답
  2. 만료기간이 지난 Token인 경우: 해당정보에 대한 결과코드/메시지 + 새로 발행한 Token를 Body에 담아 응답

**Comment by developer-Fwa** [comment]
- 현 프로세스
  1. 로그인 시 claim이 없는 형태의 Token 발행 
  2. Token 검증이 필요한 API요청 시 Token의 유효성 확인
  3. 만료된 Token일 경우 새로 발행한 Token 응답처리

- 검토사항
  1. 발급된 Token과 요청한 API의 추가적인 유효성 확인 프로세스
     - 유효성 확인을 위한 claim값 정의 (로그인ID 등)
     - API 요청 시 Token claim값 유효성 검증을 위한 식별 데이터 전송 규약 정의 (로그인ID를 Header, Body에 포함여부 등)
