### ISSUE TITLE
REST API 보안 적용 검토

### ISSUE THREAD

**Issue by cloudwisx** [SNUH-SMILE/web-app#6]

**Comment by ksangho0823** [comment]
IITP > Documents > General > 01.분석설계 > 03. REST API 보안검토 폴더 문서 공유 완료

**Comment by cloudwisx** [comment]
12/28(화), 유라클과 협의결과]
1. 로그인시 Token을 발행하여 Body에 담아 응답. Token의 만료시간은 24시간
2. 로그인을 제외한 모든 요청시 Header에(Key: Authorization, Value: bearer Token) Token을 담아 요청
3. Token의 유효성 검사
   3.1) web-app에서 발행하지 않았거나 유효하지 않은 Token인 경우: 해당 정보에 대한 결과코드/메시지를 Body에 담아 응답
   3.2) 만료기간이 지난 Token인 경우: 해당정보에 대한 결과코드/메시지 + 새로 발행한 Token를 Body에 담아 응답
